baseURL = "https://www.kevinmdeluca.com/"
languageCode = "en-us"
title = "Kevin DeLuca"
theme = "researcher"

[outputs]
  home = ["HTML", "JSON"]

[params]
  author = "Kevin DeLuca"
  description = "Assistant Professor of Political Science at Yale University"
  
  # Social media links (optional)
  # twitter = "your-twitter"
  # github = "your-github"
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2
    
  [[menu.main]]
    identifier = "media"
    name = "Media"
    url = "/media/"
    weight = 3
    
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/s/kdl_CV_short.pdf"
    weight = 4
    
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://substack.com/your-username"
    weight = 5
