baseURL = "https://kevin-deluca-polisci.github.io/KD-website/"
languageCode = "en-us"
title = "Kevin DeLuca"

[outputs]
  home = ["HTML"]

[params]
  author = "Kevin DeLuca"
  description = "Assistant Professor of Political Science at Yale University"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2
    
  [[menu.main]]
    identifier = "media"
    name = "Media"
    url = "/media/"
    weight = 3
    
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/s/kdl_CV_short.pdf"
    weight = 4
    
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://locomotivewithoutrails.substack.com/"
    weight = 5
